### ISSUE TITLE
creating patterns using jade

### ISSUE THREAD

**Issue by mcecot** [PebbleRoad/tapestry#22]
i would like to use jade to create new patterns.
my impression is that you are already using jade. 

if i place a jade file in src/patterns/pattern/written/in.jade
will generate a file patterns/pattern/written/in.md

but what about the frontmatter informations, how can i add a pattern 
name and description using jade?

**Comment by rmdort** [comment]
Yes. You can use jade files to create new patterns. They will be converted to markdown file with frontmatter. This is how our Jade files look like

````
| ---
| name: Alert success
| description: |
|     ### What
|     Page­ level information or service alert. Critical updates with a defined time period should | be pushed using the alert box.
| 
|     ### Use when
|     For page­level critical updates.
| ---
.alert.alert--success
    .alert__title
        | This is a success alert
    .alert__body
        | More body text
    a.alert_close(href="#")
````

**Comment by mcecot** [comment]
sorry for this late reply and thank you it works. i luv it.
