### ISSUE TITLE
Can't edit index.html - changes are overwritten by automatically generated file

### ISSUE THREAD

**Issue by asigrist** [PebbleRoad/tapestry#29]
Hi, so, I just downloaded Tapestry and tried to add in the Angular Bootstrap library - I installed it with Bower no problem, but when I add the script tag to include its .js file and restart my server (using "gulp patterns" per the instructions), the index.html gets automatically generated and my script tag is erased.

I also then just followed the directions on how to use the app, "Inject your own CSS by editing index.html and add your own patterns" thinking maybe it's some issue with javascript files, but the index.html file is overwritten completely again. It's essentially unusable if I can't update it at all...is there another spot in the app where I should be adding references to additional css and js files so they'll get included when index.html is built? Thanks!

**Comment by rmdort** [comment]
Tapestry uses Jade to generate the htmls

Please edit Jade template files in `src/jade/`

**Comment by asigrist** [comment]
Weird, I tried that before I wrote and it didn't seem to work, but sure
enough it works now. (maybe I didn't restart my server). Thanks for the
prompt reply!
