### ISSUE TITLE
'gulp build' not building properly

### ISSUE THREAD

**Issue by andyra** [PebbleRoad/tapestry#6]
Tapestry seems completely great, but I'm having trouble building the site from your repo. When I run `gulp build`, flat HTML files are created in the build directory, but the content isn't showing up. The menus aren't generated and all the content in /build/patterns are still in Markdown format, not HTML. `gulp build` is there to create a static version of the site, right?

![tapestry-build-problems](https://cloud.githubusercontent.com/assets/784440/2661568/a019a9d2-c02e-11e3-8ce3-e2da1b378437.png)

**Comment by ericnation** [comment]
I'm also experiencing this issue. Uploaded the src folder to my server. In the console I'm getting 404 errors for /src/json/1.elements.json, /src/json/2.components.json, and /src/json/3.templates.json. Displays fine on http://localhost:8000/#!/
